FAIL
Kernel panic in run: PANIC at ../../threads/thread.c:323 in thread_current(): assertion `is_thread(t)' failed.
Call stack: 0x8004216fcb 0x80042072a5 0x800420ad6b 0x800420ac6a 0x800420bb68 0x800420bc30 0x800420c1d6 0x800421e8ff 0x800421d8e6 0x800421b219 0x800421ae81 0x800421a8be 0x800421a62b 0x80042077f1
Translation of call stack:
0x0000008004216fcb: debug_panic (lib/kernel/debug.c:32)
0x00000080042072a5: thread_current (threads/thread.c:324)
0x000000800420ad6b: lock_held_by_current_thread (threads/synch.c:280)
0x000000800420ac6a: lock_release (threads/synch.c:261)
0x000000800420bb68: palloc_get_multiple (threads/palloc.c:271 (discriminator 4))
0x000000800420bc30: palloc_get_page (threads/palloc.c:297)
0x000000800420c1d6: malloc (threads/malloc.c:122)
0x000000800421e8ff: inode_read_at (filesys/inode.c:210)
0x000000800421d8e6: file_read (filesys/file.c:74)
0x000000800421b219: load_segment (userprog/process.c:585)
0x000000800421ae81: load (userprog/process.c:463)
0x000000800421a8be: process_exec (userprog/process.c:195)
0x000000800421a62b: initd (userprog/process.c:79)
0x00000080042077f1: kernel_thread (threads/thread.c:501)
